version: "3.9"

services:

  klarna:
    build: .
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:5000 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
